application: reformly
version: 1
runtime: python27
api_version: 1
# threadsafe: true
inbound_services:
- mail


handlers:
- url: /json
  static_dir: json
- url: /css
  static_dir: css
- url: /js
  static_dir: js


- url: /.*
  script: appengine.app

# - url: /_ah/mail/admin@.*reformly\.appspotmail\.com 
#   script: email_admin.py 
#   login: admin
# - url: /_ah/mail/support@.*reformly\.appspotmail\.com 
#   script: email_support.py 
#   login: admin
- url: /_ah/mail/.+ 
  script: email_catchall.py 
  login: admin

libraries:
- name: jinja2
  version: latest



